# Azure Storage Container Upload
name: Azure Storage Container Upload

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  upload:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure Blob Upload with Destination folder defined
      uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
      with:
        connection_string: ${{ secrets.NETWORKS_DATA_CONTAINER_CONNECTION_STRING }}
        container_name: vgiwebprodopendssnetworks
        source_folder: vgiwebprodopendssnetworks/
        destination_folder: ""
        clean_destination_folder: true
